const JAVASCRIPT_MODULE_TYPE_DYNAMIC = "javascript/dynamic";
const JAVASCRIPT_MODULE_TYPE_ESM = "javascript/esm";
const JAVASCRIPT_MODULE_TYPE_AUTO = "javascript/auto";

export {
  JAVASCRIPT_MODULE_TYPE_DYNAMIC,
  JAVASCRIPT_MODULE_TYPE_ESM,
  JAVASCRIPT_MODULE_TYPE_AUTO,
};
